services:
  - type: web
    name: logiapi
    env: node
    plan: free # or basic
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false 
      - key: REDIS_URL
        sync: false 
      - key: JWT_SECRET
        generateValue: true 
